### PR TITLE
Added in Omniauth google

### PR DESCRIPTION
**Pull request by brihong**
# Trello Ticket: 
https://trello.com/c/R7r29tTu/9-social-media-authentication

# Description:

- Added in social media authentication using the omniauth-google-oauth2 gem
- To hide the Client Keys and Secret IDs, implemented the Figaro gem
- Added the columns "provider" (string) and "uid" (string) to your User model

# Documentation Referenced:

- https://github.com/zquestz/omniauth-google-oauth2

- https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview

### CODE REVIEW

**Comment by brihong** [comment]
Hey Team, looks like there's slight conflict with the 
`ActiveRecord::Schema.define(version: 20_191_114_165_655) do` line. Should be an easy edit and merge. Thank you!

**Comment by brephelps** [comment]
@brihong When I try to test this out, I get a 400 error, is this the expected issue mentioned above? 
image

**Comment by brihong** [comment]
Ah Thanks @brephelps for testing this out. Since we are using devise, I referenced [this OmniAuth: Overview with Devise](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview). 
However, I think the issue could be due to Figaro hiding the actual 'GOOGLE_CLIENT_ID' and 'GOOGLE_SECRET_KEY' in the application.yml which isn't uploaded to github.
Just pushed a new commit and have added `Figaro.load` to the devise.rb file and the Sign in with Google function works on my end. (though I am able to access the application.yml file locally).

**Comment by brephelps** [comment]
Awesome, I will test it out with the changes! Thank you!

**Comment by brephelps** [comment]
Hmm I checked out all three documentations listed, but I'm still getting the same error. I have also run `bundle install` and `rake db:migrate` but that didn't help. Maybe @R-Currie can test this and merge if it works for him - perhaps it's just user error on my end!

**Comment by brihong** [comment]
Yeah I’ll do more research about how omniauth, devise and figaro can work together. Can ask my mentor about this one too. Since this was optional, we can close the PR and move it back to Backlog/In-Progress in the meantime. Thanks !

**Comment by R-Currie** [comment]
@brihong It also isn't working on my end.  Did you set up the google API keys through the Google Developers Console?  If so, I think I have a work around

**Comment by brihong** [comment]
Hey @R-Currie , ok great! Yes I created it through the Google Developers Console. 
Let me share the details on our Slack channel

**Comment by R-Currie** [comment]
Works perfectly @brihong

**Pull request merged**
