### PR TITLE
Move to logic

### PR DESCRIPTION
**Pull request by R-Currie**
# Trello Ticket: 

https://trello.com/c/N3yWZvJR/21-capture-logic

# Description: 

Checks if the space it is trying to move to is empty, if it is not then it checks to see if the piece in it is the enemy color and handles cases from there.

# Documentation Referenced:

None

### CODE REVIEW

**Comment by brephelps** [comment]
@R-Currie I think you may need to pull/rebase with the master branch? it looks like you're hitting errors on the RSpec tests.

**Comment by R-Currie** [comment]
> @R-Currie I think you may need to pull/rebase with the master branch? it looks like you're hitting errors on the RSpec tests. Or maybe your new code effects the tests that have already been written.

I think it might be because of something I just edited, but if this one doesn't work I'll rebase.

**Comment by brephelps** [comment]
Hey @ivanperez002 @R-Currie Can one of you explain to me how this method works? I'm confused as to what @game[new_x][new_y] should be doing? When I run it in my Rails Console to test, it doesn't seem to work, so I just want to understand this better so I can figure out what I am doing wrong.

**Comment by R-Currie** [comment]
@brephelps the goal is to grab the coordinates of where the piece is trying to move to and then determine if the space is empty.  If it doesn't work as is, then maybe I could change it to be more similar to enemy_piece where it uses .where.  Do you think that would work?

**Comment by brephelps** [comment]
@R-Currie I think the issue is that @game is just an array with the game data in it; not necessarily any piece data? So I don't know that the @game is even aware of which spaces are currently taken or available (see below shot of what is housed in @game. 
image


So I'm thinking we'd have to rework this somehow. I will try to think of any changes we can easily make, but if not, maybe we can discuss with Sam and Wilson during our meeting?

**Comment by R-Currie** [comment]
I'll try to come up with something too.  Thanks for the input @brephelps

**Comment by brihong** [comment]
Hi @R-Currie , I think it looks good. But just for my understanding, regarding the code:

>    if space === nil
      self.update_attributes({ x_position: new_x, y_position: new_y })
      return true
    end

if a space is empty, then update the chesspieces' x and y position to the new x & y coordinates. 

Then the below code would account for if a opponent piece is in that space, call the capture method and update the chesspiece with the new x & y coordinates.
>    if space.color != self.color
      capture_piece(new_x, new_y)
      self.update_attributes({ x_position: new_x, y_position: new_y })
      true
    else
      false
    end
  end

Sorry that I am a total newbie :) 
Let's discuss more in the meeting soon

**Comment by R-Currie** [comment]
That's exactly right @brihong

**Comment by ivanperez002** [comment]
@R-Currie , very nice modifications.

**Pull request merged**
