### PR TITLE
Board class

### PR DESCRIPTION
**Pull request by ivanperez002**
# Trello Ticket: 
https://trello.com/c/NtwHD6DQ/13-write-the-isobstructed-method

# Description:
Second Attempt at the Obstructed method. This one creates a board model with the method of obstructed. 

# Documentation Referenced:
None

### CODE REVIEW

**Comment by brephelps** [comment]
Hi team! I discussed this method with my mentor, but he recommended that we put this class inside the ChessPieces model. Maybe we can discuss at our meeting tomorrow? @brihong @R-Currie @ivanperez002

**Comment by brihong** [comment]
> Hi team! I discussed this method with my mentor, but he recommended that we put this class inside the ChessPieces model. Maybe we can discuss at our meeting tomorrow? @brihong @R-Currie @ivanperez002

Hi Bre, that looks to be the case judging from other team's github setup of having the obstructed method inside the Chesspiece model.
Should this PR pass the TravisCI checks before we approve it?

**Comment by ivanperez002** [comment]
Hey all I think it is failing solely because of the rupocop errors it is finding. Don’t see any other errors in the details page. 

My bad, as I keep forgetting to run the rubocop command before pushing to github...

**Comment by brephelps** [comment]
I think we’ve confused ourselves lol. Last night I think we said to move the is_obstructed? method to the Board model, but in Github our comments all say to move it to the ChessPieces model since the pieces themselves will be obstructed, not the board or game? Just want to make sure before approving? If we want to move to ChessPiece, I can do so now and resubmit.

Also, I’ve added some lines to the rubocop.yml so our tests don’t keep failing - let me know if you think we should edit these numbers:

Metrics/AbcSize:
 Max: 50
Metrics/MethodLength:
 Max: 25
Naming/PredicateName:
 Enabled: false

**Pull request merged**
