### PR TITLE
add valid_move? for the king piece

### PR DESCRIPTION
**Pull request by R-Currie**
# Trello Ticket: 
https://trello.com/c/xbR1x0zp/19-validmove-for-the-king

# Description:
Added a valid_move? method for the king.  The only thing I am unsure of is using @rows to check if there is a piece already there, so I used the same logic as Ivan in the is_obstructed method.

# Documentation Referenced:
None

### CODE REVIEW

**Comment by R-Currie** [comment]
You're right @brihong, that's embarrassing.   Just pushed the fix.

**Comment by brihong** [comment]
Oh no worries! 
Let's give @brephelps and @ivanperez002 a chance to check it out as well before merging

**Comment by ivanperez002** [comment]
@R-Currie , good thinking on this method. Took me a while to grasp how you did it. very nice. 

only item I see of concern is the last check against "@rows[x2,y2] == false". Since we moved it from the board model to the game model. and that the game pieces will be on the @game instance variable. we should be checking it at @games[x2,y2] as i think you are calling the obstructed method here? we could just do obstructed?(x2,y2)?

but the valid move portion is looking good.

**Comment by R-Currie** [comment]
That's the part I wasn't sure of.  I just posted this on slack, but the board model is not pushed to github, so I made some educated guesses.  I'll change it when I can reference the model.

**Pull request merged**
