### PR TITLE
Stalemate

### PR DESCRIPTION
**Pull request by brephelps**
# Trello Ticket: 
https://trello.com/c/mpwvT1fR/40-stalemate

# Description:
Made a LOT of changes to some of our code and added a lot of code as well. The functionality is currently working and passing all rspec tests. Not super showy on the Games#show page, but it's there (see pic).

You will want to merge the PR for `Game index turn updates first`, as I have that code in this branch.

image

# Documentation Referenced:

### CODE REVIEW

**Comment by brephelps** [comment]
May want to use the Squash and Merge to squash all of my commits into one 

image

**Comment by brephelps** [comment]
You will want to merge the PR for `Game index turn updates` first, as I have that code in this branch.

**Comment by R-Currie** [comment]
Untitled
I had the same thing as Ivan on the first time I tried it, then the second time this happened.  And my pawns starting moving by themselves.

**Comment by R-Currie** [comment]
@brephelps I messed with the console so it was in a stalemate and it worked!  That's crazy.  Not sure where the pawn issue comes from, but good job

**Comment by brephelps** [comment]
@R-Currie @ivanperez002 I am adding code to each of the chess pieces now to fix the moving pieces!

**Comment by brihong** [comment]
Looks good on my end as well Bre! Great Job!
stalemate-test

**Pull request merged**
