### PR TITLE
Setting up crud

### PR DESCRIPTION
**Pull request by brephelps**

### CODE REVIEW

**Comment by brihong** [comment]
Hi Team,
Totally new to reviewing pull requests, so apologies if I am mistaken. However, I noticed that among the [Files Changed for this Pull Request were the 'test/' folders](https://github.com/Not-just-chess/not-just-chess/pull/4/files). It seems for our testing environment, we proceeded with Rspec. So after looking at [Files Changed on Pull Request #2 "Added Rspec.."](https://github.com/Not-just-chess/not-just-chess/pull/2/files), the **test/** folders were deleted and **spec/** folders were used instead. 
Wasn't sure if pushing this update to master will cause problems later on. Looking forward to your thoughts!

**Comment by brephelps** [comment]
Hi @brihong I believe (and anyone can correct me if I'm wrong) that when you spin up a Rails app, it creates the Test folders as a default for your testing code. However, since we are using RSpec, this should actually replace those Test folders (used Grammable as a reference). Our Test environment should be unaffected by these changes. 

I hope this helps (and that I didn't get it completely wrong lol).

**Comment by brihong** [comment]
Thanks @brephelps . That makes sense and actually looks like the branch conflicts do not involve those testing folders.

Looking at the branch conflict for the Games Controller file, should there be an 'end' on line 11? 

For the branch conflict on the routes file, it seems we should determine where the root of the index should be (pages or games). Let's get Robert and Ivan's input as well

**Comment by brephelps** [comment]
@ivanperez002 @R-Currie can you take a look at Brian's comment above and let us know your thoughts? I believe the index should be Games (and that Pages was simply created for that first task), but let us know what you think.

**Comment by R-Currie** [comment]
Bre is right.  I just made the pages controller because I needed something to have an index page (as per the instructions).  It definitely should be replaced by the games controller and probably just deleted.

**Comment by brihong** [comment]
```
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'games#index'
  resources :games, only: [:new, :show, :create]

end

```
Thanks Bre and Robert to confirming. Just to make sure I don't delete any important lines, the above updated code for the routes.rb file should resolve this branch conflict.

**Comment by ivanperez002** [comment]
Sorry for the late response @brephelps  and @brihong, but in response to the test files causing an issue, I don't believe they will cause an issue with Rspec. 

@brihong the updated code looks good

**Pull request merged**
