### PR TITLE
added forfeit scope to game index

### PR DESCRIPTION
**Pull request by brephelps**
# Trello Ticket: 
https://trello.com/c/rqRG36fO/48-add-forefeited-clause-to-game-index-loop

# Description:
Added active/forfeited scope to the game model
Updated the game controller index method, so index page doesn't display forfeited games

# Documentation Referenced:
Just wanted to knock this one off our backlog

### CODE REVIEW

**Comment by brihong** [comment]
Hey @brephelps looks good on my end. I've looked over the branch conflict twice and can't seem to find the differerence. I'm assuming we can delete master and proceed with `game_index_add_forfeit` version of the schema? Thanks!

**Comment by R-Currie** [comment]
Looks good, just have to handle the schema conflict

**Comment by brephelps** [comment]
@R-Currie @brihong Are you still seeing a conflict? It looks green on my end.

**Comment by brihong** [comment]
All good now @brephelps !
Merging

**Pull request merged**
