### PR TITLE
Valid Moves for Rook

### PR DESCRIPTION
**Pull request by brihong**
# Trello Ticket: 
https://trello.com/c/pVe7VI18/25-validmove-for-the-rook

# Description:
- Valid Moves for the Rook (moves vertically and horizontally without obstructions)
- Added valid_move? to rook.rb
- Created Rspec tests for valid and invalid moves

# Documentation Referenced:
-

### CODE REVIEW

**Comment by brephelps** [comment]
@brihong It looks like my testing results aren't consistent? It may be that I am just using the incorrect locations; otherwise, I'm thinking there may be a rework needed on that chained statement at the end of your method. 
image

image

**Comment by brihong** [comment]
Hey Bre, Thanks for checking. Regarding the last chained statement: on my end, I adjusted the !off_board? method to be `!off_board?(x2, y2)`.
It looks like the changes are reflected in the Files Changed tab as well

**Comment by brephelps** [comment]
It still looks like I'm getting inconsistencies, but maybe someone else can test to be sure before you spend any time on it 
image

**Comment by brihong** [comment]
Hmm digging through the differences between master and this PR, I found these changes in the chess_piece.rb is_obstructed? method
It looks like master has: 

>  x_delta = x2 - x1
    y_delta = y2 - y1
    x_dir = x_delta / x_delta.abs
    y_dir = y_delta / y_delta.abs

Then in the PR:
>  x_delta = x2 - x1
    y_delta = y2 - y1
    x_dir = x_delta.zero? ? 0 : x_delta / x_delta.abs
    y_dir = y_delta.zero? ? 0 : y_delta / y_delta.abs

**Comment by ivanperez002** [comment]
@brihong , I believe that correction to the PR version of the delta formulas is a good change. I was having problems with my Queen Valid Moves RSPEC test becuase x_dir or y_dir would return "cant divide by 0" that if checks against this issue. @brephelps good solution

**Comment by brihong** [comment]
Hey @ivanperez002, if you have the time, can you pull the rook-moves branch and check if the rspec tests are passing?

**Comment by ivanperez002** [comment]
@brihong , I actually was looking at that right now. And the test are passin on my end. No issues with the RSPEC tests it seems. I do have one question though: why is the starting location of your pieces at 3,3? Just curious as i see the Rook at only the corners of the board to start. This is just for my information

**Comment by brihong** [comment]
Hey @ivanperez002 , good question. I think I wanted to simulate a situation where the rook is able to move vertically up and down, horizontally left and right, thus the current_location of (3, 3)

**Comment by ivanperez002** [comment]
Looks good to me. Merging

**Pull request merged**
