### PR TITLE
Pawn promotion new

### PR DESCRIPTION
**Pull request by ivanperez002**
# Trello Ticket: 
https://trello.com/c/T34prnWj/46-pawn-promotion

# Description:
Add the ability for a pawn to be promoted into any of the following types. You will need to think through how to prompt the user for what piece they want to take (queen, knight, or if they’re in a case where doing so would cause a stalemate a rook or bishop)

# Documentation Referenced:

### CODE REVIEW

**Comment by brihong** [comment]
Really nice work @ivanperez002 !
Just tested it out on my local branch and it works great. 
I'll let @R-Currie and @brephelps  have a chance to test out as well

**Comment by brephelps** [comment]
Womp. I'm having some issues testing this, so I'll let @R-Currie confirm/merge. 

I am getting a bar in the middle of the screen... surprisingly, when you click on it, it triggers the modal. However, I cannot move my pawn into that final square, and im not able to change what the pawn is. 

image

**Comment by R-Currie** [comment]
I'm having the same issue as Bre with regards to the bar running across the screen.  I also can't move the black player even when signing in with a separate email, so I can't even get far enough to see if the pawn can change.

**Comment by R-Currie** [comment]
I have a solution.  Change the styling on the button to style="display: none" and it only pops up when needed.

**Comment by ivanperez002** [comment]
Hey everyone. So technicallllllyyyyy the bar is not a bug. It is actually a button on the html that launches the modal. Just had to leave it there as when I took it off the JS stopped functioning and I couldn’t move any pieces. So I removed the text on the button for the time being

**Comment by ivanperez002** [comment]
Well Robert found the solution. Haha. Thanks !!

**Comment by R-Currie** [comment]
Let me know if what i pushed looks good to you and I'll merge it

**Comment by ivanperez002** [comment]
very nice. looks good to me
@R-Currie

**Comment by brephelps** [comment]
@R-Currie @ivanperez002 were all of the checks failing when we merged? do we need to go find these issues or were they just rubocop ?

**Comment by brephelps** [comment]
Okay, I pulled it down and it looks like it's just rubocop, so we'll need to make sure someone runs that before the next merge :)

**Pull request merged**
